apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10g
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs_share
    server: 45.117.80.150

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10g
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      node: k8s-nodew1
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-10g
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: volume-nginx
              mountPath: /usr/share/nginx/html
      nodeSelector:
        kubernetes.io/hostname: k8s-nodew1 # chọn node worker nfs sẽ deploy pod replicas=2, khi tạo 2 pod thì sẽ tạo trên cùng 1 node worker
      volumes:
        - name: volume-nginx
          persistentVolumeClaim:
            claimName: pvc-10g
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - name: nginx
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx

