apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10g
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 103.101.162.145:3260  # IP port iSCSI server
    iqn: iqn.1991-05.com.microsoft:k8s-iscsi-targe-target1-target  # iSCSI target đã triển khai trên window server 2022
    lun: 0    #LUN có thể vào iSCSI target server click phải Disk trong mục `ISCSI VITUAL DISK` chọn Properties đễ xem giá trị LUN
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10g
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: iscsi-volume
          mountPath: /usr/share/nginx/html   # thư mục web của service nginx
      volumes:
      - name: iscsi-volume
        persistentVolumeClaim:
          claimName: pvc-10g  # pod sử dụng storage của pvc-10g

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - name: nginx
      nodePort: 30070  # port public đễ bên ngoài truy cập
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
